### ISSUE TITLE
landmarks.txt file

### ISSUE THREAD

**Issue by weichen55** [grigala/3DMMDepthFitting#9]
Hi, I am trying to reproduce the work but found that  there is no landmarks.txt available for testing.
Can you tell me where i can find the file?

**Comment by grigala** [comment]
Hi @weichen55, sorry about that, must have lost during the project migration. 

Attaching it here, will fix in the repo later. 

[landmarks.txt](https://github.com/grigala/3DMMDepthFitting/files/11713055/landmarks.txt)

**Comment by weichen55** [comment]
Thank you very much, really appreciated.
